version: '3'
services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - db
  frontend:
  container_name: SalScheduling
  image: sal-scheduling
    build: ./client
    ports:
      - "8095:80"
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: business_scheduling
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
